stages:
  - build
  - test
  - deploy
  - clean

Celery_image_build:
  stage: build
  script:
    - echo "Celery build, Dockerfile:"
    - cat Dockerfile
    - docker build  -t Cecery:$CI_PIPELINE_ID .
  
Celery_container_deploy1:
    stage: deploy
    script:
      - docker run --name celery-container -d $IMAGE_TAG
      

